import { z } from "zod";
import type { AIProvider } from "./providers";

const RiskLevel = z.enum(["critical", "high", "medium", "low", "info"]);
type RiskLevel = z.infer<typeof RiskLevel>;

interface RiskAssessment {
  overallRisk: RiskLevel;
  summary: string;
  findings: Finding[];
  markdown: string;
}

interface Finding {
  resource: string;
  risk: RiskLevel;
  reason: string;
}

const RISK_ICONS: Record<RiskLevel, string> = {
  critical: "🔴",
  high: "🟠",
  medium: "🟡",
  low: "🟢",
  info: "🔵",
};

const SYSTEM_PROMPT = `You are a Terraform infrastructure risk assessor. You analyze Terraform plan changes and produce structured risk assessments.

You MUST respond with valid JSON matching this exact schema:
{
  "overall_risk": "critical" | "high" | "medium" | "low" | "info",
  "summary": "A 1-2 sentence summary of the overall risk posture",
  "findings": [
    {
      "resource": "resource address from the plan",
      "risk": "critical" | "high" | "medium" | "low" | "info",
      "reason": "Brief explanation of the risk"
    }
  ]
}

Risk level guidelines:
- **critical**: Destruction of stateful resources (databases, storage), broad IAM policy changes, security group rules opening 0.0.0.0/0, removing encryption, deleting backups, changes to production-critical infrastructure that could cause outages
- **high**: Resource replacements (destroy + create), modifications to security-related resources (IAM roles, policies, security groups, KMS keys), changes to networking (VPCs, subnets, route tables), modifications to load balancers or DNS
- **medium**: In-place updates to existing resources, scaling changes, tag modifications on important resources, configuration changes to compute instances
- **low**: Adding new resources with no destruction, tag-only changes, output modifications, adding new security rules that are restrictive
- **info**: No-op changes, read-only data source additions, cosmetic changes, comment-only modifications

Always err on the side of caution — if a change could be risky, rate it higher. Consider blast radius: a single risky change should elevate the overall risk.

Respond with ONLY the JSON object, no markdown fences or additional text.`;

const ResponseSchema = z.object({
  overall_risk: RiskLevel,
  summary: z.string(),
  findings: z.array(
    z.object({
      resource: z.string(),
      risk: RiskLevel,
      reason: z.string(),
    })
  ),
});

export const assessRisk = async (
  provider: AIProvider,
  planSummary: string
): Promise<RiskAssessment> => {
  const response = await provider.complete({
    systemPrompt: SYSTEM_PROMPT,
    userPrompt: `Analyze the following Terraform plan changes and provide a risk assessment:\n\n${planSummary}`,
  });

  let parsed: z.infer<typeof ResponseSchema>;
  try {
    // Handle potential markdown fences around JSON
    const cleaned = response.content
      .replace(/^```json?\n?/m, "")
      .replace(/\n?```$/m, "")
      .trim();
    parsed = ResponseSchema.parse(JSON.parse(cleaned));
  } catch (err) {
    throw new Error(
      `Failed to parse AI response as valid risk assessment JSON: ${err}\n\nRaw response:\n${response.content}`
    );
  }

  const findings: Finding[] = parsed.findings.map((f) => ({
    resource: f.resource,
    risk: f.risk,
    reason: f.reason,
  }));

  const markdown = formatMarkdown(parsed.overall_risk, parsed.summary, findings);

  return {
    overallRisk: parsed.overall_risk,
    summary: parsed.summary,
    findings,
    markdown,
  };
};

const formatMarkdown = (
  overallRisk: RiskLevel,
  summary: string,
  findings: Finding[]
): string => {
  const lines: string[] = [];

  lines.push(`## ${RISK_ICONS[overallRisk]} Terraform Risk Assessment: **${overallRisk.toUpperCase()}**`);
  lines.push("");
  lines.push(summary);
  lines.push("");

  if (findings.length > 0) {
    lines.push("### Findings");
    lines.push("");
    lines.push("| Risk | Resource | Reason |");
    lines.push("|------|----------|--------|");

    // Sort findings by severity
    const order: Record<RiskLevel, number> = { critical: 0, high: 1, medium: 2, low: 3, info: 4 };
    const sorted = [...findings].sort((a, b) => order[a.risk] - order[b.risk]);

    for (const f of sorted) {
      lines.push(`| ${RISK_ICONS[f.risk]} ${f.risk} | \`${f.resource}\` | ${f.reason} |`);
    }
  } else {
    lines.push("No specific findings.");
  }

  lines.push("");
  lines.push("---");
  lines.push("*Generated by [Terraform Risk Assessor](https://github.com/liamjohnston/terraform-risk-accessor)*");

  return lines.join("\n");
};

export type { RiskAssessment, RiskLevel, Finding };
