name: Push to Main

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  bump-version:
    name: Bump Action Version
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Git config
        run: |
          git config user.name actions-bot
          git config user.email actions-bot@users.noreply.github.com

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Install & Build
        run: |
          bun install --frozen-lockfile --production
          bun build src/index.ts --outdir=dist --target=node

      - name: Bump Version
        run: |
          git add dist/index.js
          bunx commit-and-tag-version@12.5.0 --commit-all
          git push --follow-tags origin main
          echo "TAG_VERSION=$(git tag --points-at HEAD)" >> $GITHUB_ENV

      - name: Release
        uses: softprops/action-gh-release@v3.0.0
        with:
          tag_name: ${{ env.TAG_VERSION }}
          make_latest: true

      - name: Update Major Version Release
        run: |
          TAG_MAJOR_VERSION=$(echo "V$(echo "${TAG_VERSION#v}" | cut -d. -f1)")
          echo "TAG_MAJOR_VERSION=${TAG_MAJOR_VERSION}" >> $GITHUB_ENV
          git tag -d ${TAG_MAJOR_VERSION} 2>/dev/null || echo "New major version"
          git tag ${TAG_MAJOR_VERSION}
          git push origin ${TAG_MAJOR_VERSION} --force

      - name: Update Major Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.TAG_MAJOR_VERSION }}
